# Kraken SoC Constraints
# Xilinx Artix-7 xc7a100tcsg324-1

# System Clock (50 MHz target for closure)
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports clk_i]
create_clock -add -name sys_clk_pin -period 20.00 -waveform {0 10} [get_ports clk_i]

# Reset Button (active low)
set_property -dict {PACKAGE_PIN D9 IOSTANDARD LVCMOS33} [get_ports rst_ni]
set_property PULLUP true [get_ports rst_ni]

# Test Enable
set_property -dict {PACKAGE_PIN C9 IOSTANDARD LVCMOS33} [get_ports test_en_i]

# Core 0 Address Bus Output (32-bit) - use pins A17, A18, B17, B18, C17, C18, D17, D18, E17, E18, F17, F18, G17, G18, H17, H18
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[0]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[1]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[2]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[3]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[4]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[5]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[6]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[7]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[8]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[9]}]
set_property -dict {PACKAGE_PIN F17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[10]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[11]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[12]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[13]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[14]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[15]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[16]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[17]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[18]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[19]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[20]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[21]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[22]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[23]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[24]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[25]}]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[26]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[27]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[28]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[29]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[30]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {core_0_addr_o[31]}]

# Core 0 Data Output (32-bit)
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[0]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[1]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[2]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[3]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[4]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[5]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[6]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[7]}]
set_property -dict {PACKAGE_PIN AA17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[8]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[9]}]
set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[10]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[11]}]
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[12]}]
set_property -dict {PACKAGE_PIN AC18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[13]}]
set_property -dict {PACKAGE_PIN AD17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[14]}]
set_property -dict {PACKAGE_PIN AD18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[15]}]
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[16]}]
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[17]}]
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[18]}]
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[19]}]
set_property -dict {PACKAGE_PIN AG17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[20]}]
set_property -dict {PACKAGE_PIN AG18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[21]}]
set_property -dict {PACKAGE_PIN AH17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[22]}]
set_property -dict {PACKAGE_PIN AH18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[23]}]
set_property -dict {PACKAGE_PIN AJ17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[24]}]
set_property -dict {PACKAGE_PIN AJ18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[25]}]
set_property -dict {PACKAGE_PIN AK17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[26]}]
set_property -dict {PACKAGE_PIN AK18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[27]}]
set_property -dict {PACKAGE_PIN AL17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[28]}]
set_property -dict {PACKAGE_PIN AL18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[29]}]
set_property -dict {PACKAGE_PIN AM17 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[30]}]
set_property -dict {PACKAGE_PIN AM18 IOSTANDARD LVCMOS33} [get_ports {core_0_data_o[31]}]

# Core 0 Request
set_property -dict {PACKAGE_PIN AN17 IOSTANDARD LVCMOS33} [get_ports core_0_req_o]

# Memory Valid/Data signals
set_property -dict {PACKAGE_PIN AN18 IOSTANDARD LVCMOS33} [get_ports mem_valid_o]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[0]}]
set_property -dict {PACKAGE_PIN B9 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[1]}]
set_property -dict {PACKAGE_PIN A9 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[2]}]
set_property -dict {PACKAGE_PIN A8 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[3]}]
set_property -dict {PACKAGE_PIN B8 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[4]}]
set_property -dict {PACKAGE_PIN C8 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[5]}]
set_property -dict {PACKAGE_PIN C7 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[6]}]
set_property -dict {PACKAGE_PIN B7 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[7]}]
set_property -dict {PACKAGE_PIN A7 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[8]}]
set_property -dict {PACKAGE_PIN D8 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[9]}]
set_property -dict {PACKAGE_PIN D7 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[10]}]
set_property -dict {PACKAGE_PIN C6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[11]}]
set_property -dict {PACKAGE_PIN B6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[12]}]
set_property -dict {PACKAGE_PIN A6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[13]}]
set_property -dict {PACKAGE_PIN A5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[14]}]
set_property -dict {PACKAGE_PIN B5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[15]}]
set_property -dict {PACKAGE_PIN C5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[16]}]
set_property -dict {PACKAGE_PIN D5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[17]}]
set_property -dict {PACKAGE_PIN E5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[18]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[19]}]
set_property -dict {PACKAGE_PIN G5 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[20]}]
set_property -dict {PACKAGE_PIN G6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[21]}]
set_property -dict {PACKAGE_PIN F6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[22]}]
set_property -dict {PACKAGE_PIN E6 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[23]}]
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[24]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[25]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[26]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[27]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[28]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[29]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[30]}]
set_property -dict {PACKAGE_PIN F2 IOSTANDARD LVCMOS33} [get_ports {mem_data_o[31]}]

# Timing constraints
set_input_delay  -clock sys_clk_pin -min 0.5 [get_ports rst_ni]
set_input_delay  -clock sys_clk_pin -min 0.5 [get_ports test_en_i]
set_output_delay -clock sys_clk_pin -min 0.5 [get_ports {core_0_addr_o[*]}]
set_output_delay -clock sys_clk_pin -min 0.5 [get_ports {core_0_data_o[*]}]
set_output_delay -clock sys_clk_pin -min 0.5 [get_ports {mem_data_o[*]}]
