# Kraken SoC Constraints File
# Maps internal debug signals to FPGA I/O pins (Artix-7 xc7a100tcsg324-1)

# Clock and Reset
set_property PACKAGE_PIN E3 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
set_property PULLDOWN true [get_ports clk_i]

set_property PACKAGE_PIN D9 [get_ports rst_ni]
set_property IOSTANDARD LVCMOS33 [get_ports rst_ni]
set_property PULLUP true [get_ports rst_ni]

set_property PACKAGE_PIN A9 [get_ports test_en_i]
set_property IOSTANDARD LVCMOS33 [get_ports test_en_i]

# Core 0 Debug Outputs
set_property PACKAGE_PIN T10 [get_ports {core_0_addr_o[0]}]
set_property PACKAGE_PIN T9 [get_ports {core_0_addr_o[1]}]
set_property PACKAGE_PIN J5 [get_ports {core_0_addr_o[2]}]
set_property PACKAGE_PIN H5 [get_ports {core_0_addr_o[3]}]
set_property PACKAGE_PIN K5 [get_ports {core_0_addr_o[4]}]
set_property PACKAGE_PIN K6 [get_ports {core_0_addr_o[5]}]
set_property PACKAGE_PIN P7 [get_ports {core_0_addr_o[6]}]
set_property PACKAGE_PIN P8 [get_ports {core_0_addr_o[7]}]
set_property PACKAGE_PIN P9 [get_ports {core_0_addr_o[8]}]
set_property PACKAGE_PIN N9 [get_ports {core_0_addr_o[9]}]
set_property PACKAGE_PIN M8 [get_ports {core_0_addr_o[10]}]
set_property PACKAGE_PIN L8 [get_ports {core_0_addr_o[11]}]
set_property PACKAGE_PIN M9 [get_ports {core_0_addr_o[12]}]
set_property PACKAGE_PIN L9 [get_ports {core_0_addr_o[13]}]
set_property PACKAGE_PIN M10 [get_ports {core_0_addr_o[14]}]
set_property PACKAGE_PIN L10 [get_ports {core_0_addr_o[15]}]
set_property PACKAGE_PIN N8 [get_ports {core_0_addr_o[16]}]
set_property PACKAGE_PIN M11 [get_ports {core_0_addr_o[17]}]
set_property PACKAGE_PIN L11 [get_ports {core_0_addr_o[18]}]
set_property PACKAGE_PIN K11 [get_ports {core_0_addr_o[19]}]
set_property PACKAGE_PIN K9 [get_ports {core_0_addr_o[20]}]
set_property PACKAGE_PIN J9 [get_ports {core_0_addr_o[21]}]
set_property PACKAGE_PIN J8 [get_ports {core_0_addr_o[22]}]
set_property PACKAGE_PIN G8 [get_ports {core_0_addr_o[23]}]
set_property PACKAGE_PIN G7 [get_ports {core_0_addr_o[24]}]
set_property PACKAGE_PIN H6 [get_ports {core_0_addr_o[25]}]
set_property PACKAGE_PIN H4 [get_ports {core_0_addr_o[26]}]
set_property PACKAGE_PIN H3 [get_ports {core_0_addr_o[27]}]
set_property PACKAGE_PIN H2 [get_ports {core_0_addr_o[28]}]
set_property PACKAGE_PIN H1 [get_ports {core_0_addr_o[29]}]
set_property PACKAGE_PIN G4 [get_ports {core_0_addr_o[30]}]
set_property PACKAGE_PIN G3 [get_ports {core_0_addr_o[31]}]

# Core 0 Data Output (32 bits)
set_property PACKAGE_PIN B4 [get_ports {core_0_data_o[0]}]
set_property PACKAGE_PIN B5 [get_ports {core_0_data_o[1]}]
set_property PACKAGE_PIN A4 [get_ports {core_0_data_o[2]}]
set_property PACKAGE_PIN A5 [get_ports {core_0_data_o[3]}]
set_property PACKAGE_PIN C5 [get_ports {core_0_data_o[4]}]
set_property PACKAGE_PIN C4 [get_ports {core_0_data_o[5]}]
set_property PACKAGE_PIN D7 [get_ports {core_0_data_o[6]}]
set_property PACKAGE_PIN D8 [get_ports {core_0_data_o[7]}]
set_property PACKAGE_PIN C7 [get_ports {core_0_data_o[8]}]
set_property PACKAGE_PIN C8 [get_ports {core_0_data_o[9]}]
set_property PACKAGE_PIN B8 [get_ports {core_0_data_o[10]}]
set_property PACKAGE_PIN B9 [get_ports {core_0_data_o[11]}]
set_property PACKAGE_PIN C9 [get_ports {core_0_data_o[12]}]
set_property PACKAGE_PIN A8 [get_ports {core_0_data_o[13]}]
set_property PACKAGE_PIN A10 [get_ports {core_0_data_o[14]}]
set_property PACKAGE_PIN D10 [get_ports {core_0_data_o[15]}]
set_property PACKAGE_PIN C11 [get_ports {core_0_data_o[16]}]
set_property PACKAGE_PIN E11 [get_ports {core_0_data_o[17]}]
set_property PACKAGE_PIN E10 [get_ports {core_0_data_o[18]}]
set_property PACKAGE_PIN D11 [get_ports {core_0_data_o[19]}]
set_property PACKAGE_PIN F11 [get_ports {core_0_data_o[20]}]
set_property PACKAGE_PIN F10 [get_ports {core_0_data_o[21]}]
set_property PACKAGE_PIN F9 [get_ports {core_0_data_o[22]}]
set_property PACKAGE_PIN G10 [get_ports {core_0_data_o[23]}]
set_property PACKAGE_PIN G9 [get_ports {core_0_data_o[24]}]
set_property PACKAGE_PIN G11 [get_ports {core_0_data_o[25]}]
set_property PACKAGE_PIN F8 [get_ports {core_0_data_o[26]}]
set_property PACKAGE_PIN G6 [get_ports {core_0_data_o[27]}]
set_property PACKAGE_PIN D6 [get_ports {core_0_data_o[28]}]
set_property PACKAGE_PIN E6 [get_ports {core_0_data_o[29]}]
set_property PACKAGE_PIN E5 [get_ports {core_0_data_o[30]}]
set_property PACKAGE_PIN D5 [get_ports {core_0_data_o[31]}]

# Core 0 Request signal
set_property PACKAGE_PIN E8 [get_ports core_0_req_o]
set_property IOSTANDARD LVCMOS33 [get_ports core_0_req_o]

# Memory Valid signal
set_property PACKAGE_PIN E7 [get_ports mem_valid_o]
set_property IOSTANDARD LVCMOS33 [get_ports mem_valid_o]

# Memory Data Output (32 bits)
set_property PACKAGE_PIN E4 [get_ports {mem_data_o[0]}]
set_property PACKAGE_PIN D4 [get_ports {mem_data_o[1]}]
set_property PACKAGE_PIN E2 [get_ports {mem_data_o[2]}]
set_property PACKAGE_PIN D3 [get_ports {mem_data_o[3]}]
set_property PACKAGE_PIN F5 [get_ports {mem_data_o[4]}]
set_property PACKAGE_PIN F4 [get_ports {mem_data_o[5]}]
set_property PACKAGE_PIN B2 [get_ports {mem_data_o[6]}]
set_property PACKAGE_PIN B1 [get_ports {mem_data_o[7]}]
set_property PACKAGE_PIN C2 [get_ports {mem_data_o[8]}]
set_property PACKAGE_PIN C1 [get_ports {mem_data_o[9]}]
set_property PACKAGE_PIN D2 [get_ports {mem_data_o[10]}]
set_property PACKAGE_PIN D1 [get_ports {mem_data_o[11]}]
set_property PACKAGE_PIN F2 [get_ports {mem_data_o[12]}]
set_property PACKAGE_PIN F1 [get_ports {mem_data_o[13]}]
set_property PACKAGE_PIN G2 [get_ports {mem_data_o[14]}]
set_property PACKAGE_PIN G1 [get_ports {mem_data_o[15]}]
set_property PACKAGE_PIN J2 [get_ports {mem_data_o[16]}]
set_property PACKAGE_PIN J1 [get_ports {mem_data_o[17]}]
set_property PACKAGE_PIN K2 [get_ports {mem_data_o[18]}]
set_property PACKAGE_PIN K1 [get_ports {mem_data_o[19]}]
set_property PACKAGE_PIN L4 [get_ports {mem_data_o[20]}]
set_property PACKAGE_PIN L3 [get_ports {mem_data_o[21]}]
set_property PACKAGE_PIN L2 [get_ports {mem_data_o[22]}]
set_property PACKAGE_PIN L1 [get_ports {mem_data_o[23]}]
set_property PACKAGE_PIN M4 [get_ports {mem_data_o[24]}]
set_property PACKAGE_PIN M3 [get_ports {mem_data_o[25]}]
set_property PACKAGE_PIN M2 [get_ports {mem_data_o[26]}]
set_property PACKAGE_PIN M1 [get_ports {mem_data_o[27]}]
set_property PACKAGE_PIN N4 [get_ports {mem_data_o[28]}]
set_property PACKAGE_PIN N3 [get_ports {mem_data_o[29]}]
set_property PACKAGE_PIN N2 [get_ports {mem_data_o[30]}]
set_property PACKAGE_PIN N1 [get_ports {mem_data_o[31]}]

# Set all outputs to LVCMOS33
set_property IOSTANDARD LVCMOS33 [get_ports core_0_addr_o*]
set_property IOSTANDARD LVCMOS33 [get_ports core_0_data_o*]
set_property IOSTANDARD LVCMOS33 [get_ports mem_data_o*]

# Set I/O slew rate and drive strength
set_property SLEW SLOW [get_ports core_0_addr_o*]
set_property DRIVE 4 [get_ports core_0_addr_o*]
set_property SLEW SLOW [get_ports core_0_data_o*]
set_property DRIVE 4 [get_ports core_0_data_o*]
set_property SLEW SLOW [get_ports mem_data_o*]
set_property DRIVE 4 [get_ports mem_data_o*]
